In [5]:
# IMPORTING THE LIBRARY

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [6]:
#DATASET LODING 
import pandas as pd

df = pd.read_csv("../data/hotel_bookings.csv")

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,7/1/2015
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,7/1/2015
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,7/2/2015
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,7/2/2015
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,7/3/2015


In [9]:
#How many rows are present 
df.shape[0]

119390

In [10]:
#how many columns are present 
df.shape[1]

32

In [13]:
#What is the size of dataset?
df.shape

(119390, 32)

In [14]:
#What are the columns name ?
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [15]:
#what are the datatype 
df.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             

In [17]:
#are there any missing values
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company         

In [18]:
#What percentage of the data missing ?

(df.isnull().sum() / len(df) * 100).sort_values(ascending=False)



company                           94.306893
agent                             13.686238
country                            0.408744
children                           0.003350
reserved_room_type                 0.000000
assigned_room_type                 0.000000
booking_changes                    0.000000
deposit_type                       0.000000
hotel                              0.000000
previous_cancellations             0.000000
days_in_waiting_list               0.000000
customer_type                      0.000000
adr                                0.000000
required_car_parking_spaces        0.000000
total_of_special_requests          0.000000
reservation_status                 0.000000
previous_bookings_not_canceled     0.000000
is_repeated_guest                  0.000000
is_canceled                        0.000000
distribution_channel               0.000000
market_segment                     0.000000
meal                               0.000000
babies                          

In [25]:
#Are there duplicate rows
df.duplicated().sum()

np.int64(31994)

In [24]:
# Q8. Are there duplicate rows?
df.duplicated().sum()

np.int64(31994)

In [26]:
#Should we remove the duplicate rows
df.duplicated().sum() > 0

np.True_

In [27]:
#How many unique hotel are there
df["hotel"].nunique()

2

In [28]:
#How many booking belong to each other 
df["hotel"].value_counts()

hotel
City Hotel      79330
Resort Hotel    40060
Name: count, dtype: int64

In [29]:
#are there missing values in children 
df["children"].isnull().sum()

np.int64(4)

In [30]:
#what values exits in children?
df["children"].unique()

array([ 0.,  1.,  2., 10.,  3., nan])

In [33]:
#are the missing country values?
df["country"].isnull().sum()

np.int64(488)

In [35]:
#how many missing values in agent?
df["agent"].isnull().sum()

np.int64(16340)

In [36]:
#How many missing values are in  company?
df["company"].isnull().sum()

np.int64(112593)

In [53]:
#Are there zero ADR values ?
(df["adr"] == 0).sum()

np.int64(1959)

In [41]:
#are there zero adult booking ?
(df["adults"]== 0).sum()

np.int64(403)

In [44]:
#What is the  minimum lead time
df["lead_time"].min()

0

In [45]:
#What is the maximum lead time
df["lead_time"].max()

737

In [47]:
#What is the average lead time
df["lead_time"].mean()

np.float64(104.01141636652986)

In [49]:
#What is the minimum adr 
df["adr"].min()

-6.38

In [50]:
#What is the maximum adr
df["adr"].max()

5400.0

In [54]:
#What is the average adr
df["adr"].mean()

np.float64(101.83112153446687)

In [55]:
#What is unique meal category
df["meal"].unique()

array(['BB', 'FB', 'HB', 'SC', 'Undefined'], dtype=object)

In [57]:
#What is unique market segment 
df["market_segment"].unique()

array(['Direct', 'Corporate', 'Online TA', 'Offline TA/TO',
       'Complementary', 'Groups', 'Undefined', 'Aviation'], dtype=object)

In [61]:
#What are unique deposits types?
df["deposit_type"].unique()

array(['No Deposit', 'Refundable', 'Non Refund'], dtype=object)

In [63]:
#What is unique customer types?
df["customer_type"].unique()

array(['Transient', 'Contract', 'Transient-Party', 'Group'], dtype=object)

In [65]:
#What percentage of booking were cancelled ?
df["is_canceled"].mean()*100

np.float64(37.041628277075134)

In [66]:
#Are there any invalid cancellatiion values?
df["is_canceled"].unique()

array([0, 1])

In [67]:
#Are the invalid hotel names ?
df["hotel"].unique()

array(['Resort Hotel', 'City Hotel'], dtype=object)

In [70]:
#are the 12 months ?
df["arrival_date_month"].nunique()

12

In [72]:
#are there missing values arrival months 
df["arrival_date_month"].isnull().sum()

np.int64(0)

In [73]:
#what years are available ?
df["arrival_date_year"].unique()

array([2015, 2016, 2017])

In [74]:
#How many booking are from reported guests 
(df["is_repeated_guest"]==1).sum()

np.int64(3810)

In [76]:
#How many booking have special request?
(df["total_of_special_requests"] > 0).sum()

np.int64(49072)

In [77]:
#how many booking required parking ?
(df["required_car_parking_spaces"] > 0).sum()

np.int64(7416)

In [78]:
#DATA TRANSFORMING
# 1) Total Nights 
# 2) Total Guests


In [81]:
#adding total nights
df["Total_Nights"] = (df["stays_in_weekend_nights"]+df["stays_in_week_nights"])


In [85]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'Total_Nights'],
      dtype='object')

In [87]:
#adding total guest 
df["Total_Guest"] = (df["adults"] + df["children"] + df["babies"])

In [88]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'Total_Nights',
       'Total_Guest'],
      dtype='object')

In [89]:


#EDA Exploratory Data Analysis

# Which hotel receives more bookings?

# Which hotel has the highest cancellation rate?  hint(group by)

# Which month receives the most bookings?

# How does lead time affect cancellation?  hint(group by)

# Which market segment produces the most bookings?


In [90]:
#Which hotel receives more bokking ?

df["hotel"].value_counts()

hotel
City Hotel      79330
Resort Hotel    40060
Name: count, dtype: int64

In [91]:
#or 

In [93]:
df.groupby("hotel").size().sort_values(ascending = False)

hotel
City Hotel      79330
Resort Hotel    40060
dtype: int64

In [99]:
#Which hotel has higest cancellation rate ?  
df.groupby("hotel")["is_canceled"].mean()*100

hotel
City Hotel      41.726963
Resort Hotel    27.763355
Name: is_canceled, dtype: float64

In [106]:
#Which months recives the most booking 
df["arrival_date_month"].value_counts()

arrival_date_month
August       13877
July         12661
May          11791
October      11160
April        11089
June         10939
September    10508
March         9794
February      8068
November      6794
December      6780
January       5929
Name: count, dtype: int64

In [105]:
#how does lead time affect the cancellation 

arrival_date_month
August       13877
July         12661
May          11791
October      11160
April        11089
June         10939
September    10508
March         9794
February      8068
November      6794
December      6780
January       5929
Name: count, dtype: int64