In [26]:
#Logistics Regression
#works on  the basis of classification
#works on category
#binary output it would be yes or no 



In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
x = [[1],[2],[3],[4],[5],[6],[7],[8],[9]]
y =[0,0,0,0,0,1,1,1,1]

In [35]:
model = LogisticRegression()
model.fit(x,y)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [38]:
predication = model.predict([[10]])
print(predication)

[1]


In [41]:
res = model.predict_proba([[10]])
print("Probability---->",res)

Probability----> [[0.00641454 0.99358546]]


In [30]:
x = [[3],[4],[5],[6],[7],[8]]
y =[0,0,0,1,1,1,]

In [31]:
model = LogisticRegression()
model.fit(x,y)
predication = model.predict([[3]])
print(predication)

[0]


In [32]:
probablity = model.predict_proba([[3]])
print("Probatity---->",probablity)

Probatity----> [[0.94275876 0.05724124]]


In [33]:
# a=0.94275876
# b=0.05724124
# a+b #-----> probality should always be 1

1.0

In [34]:
#new predicted
predication1 = model.predict([[10]])
print(predication1)

[1]


In [17]:
prob1 = model.predict_proba([[10]])
print("Probability---->",prob1)

Probatity----> [[0.00641454 0.99358546]]


In [14]:
"""
Actual value     Predication data

    1                   1----->True Postive  
    0                   0----->True Negative 
    1                   0----->False Negative 
    0                   1----->False Positive  
"""

'\nActual value     Predication data\n\n    1                   1----->True Postive \n   \n    0                   0----->True Negative \n\n    1                   0----->False Negative \n\n    0                   1----->False Positive  \n\n'

In [45]:
prob =model.predict_proba(x)
print(prob)

[[0.94275876 0.05724124]
 [0.84302673 0.15697327]
 [0.63652435 0.36347565]
 [0.3634775  0.6365225 ]
 [0.15697433 0.84302567]
 [0.05724167 0.94275833]]


In [53]:
#print only class 1
#positive data 
probability1 = []
for i in prob:
    probability1.append(i[1])
print(probability1)
    
    

[np.float64(0.057241238096216895), np.float64(0.1569732726997854), np.float64(0.36347564850626857), np.float64(0.6365224985449083), np.float64(0.8430256674588728), np.float64(0.9427583297047981)]


In [55]:
threshold = 0.5
#p<1---> 0
#p>t---->1
predication=[]

for i in probability1:
    if i >= threshold:
        predication.append(1)

    else:
        predication.append(0)
print(predication)


[0, 0, 0, 1, 1, 1]


In [56]:
print("Actaul_Predication")
print(y)
print()
print("Model_Predication")
print(predication)

Actaul_Predication
[0, 0, 0, 1, 1, 1]

Model_Predication
[0, 0, 0, 1, 1, 1]


In [58]:
from sklearn.metrics import confusion_matrix

In [59]:
cm = confusion_matrix(y,predication)
print(cm)

[[3 0]
 [0 3]]


In [70]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y,predication)
print(accuracy)

1.0


In [73]:
from sklearn.metrics import precision_score
preci = precision_score(y,predication)
print(preci)

1.0


In [74]:
#precision = TP/ TP+FP
#recal = TP/TP+
#F1 = 2* precision 

In [78]:
from sklearn.metrics import recall_score
rs = recall_score(y,predication)
print(rs)

1.0


In [80]:
from sklearn.metrics import f1_score
f1 = f1_score(y,predication)
print(f1)

1.0


In [82]:
# from sklearn.metrics import(accuracy_score , precision_score , precision_score , recall_score , f1_score)
#can use this aslo

In [96]:
a = [[2.5],[3.5],[4.5] ,[5]]
b = [1,0,1,1]

In [97]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()


In [98]:
model.fit(a,b)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [111]:
predication = model.predict([[3.5]])
print(predication)

[1]


In [112]:
res = model.predict_proba([[10]])
print("Probability---->",res)

Probability----> [[0.07848272 0.92151728]]


In [113]:
prob =model.predict_proba(a)
print(prob)

[[0.3087371  0.6912629 ]
 [0.2636703  0.7363297 ]
 [0.22305921 0.77694079]
 [0.20450029 0.79549971]]


In [114]:
#print only class 1
#positive data 
probability2 = []
for i in prob:
    probability2.append(i[1])
print(probability2)
    
    

[np.float64(0.6912628984887714), np.float64(0.736329695074202), np.float64(0.776940789656798), np.float64(0.7954997096251852)]


In [106]:
print("Actaul_Predication")
print(b)
print()
print("Model_Predication")
print(predication)

Actaul_Predication
[1, 0, 1, 1]

Model_Predication
[1]


In [115]:
predication_a = model.predict(a)
print(predication_a)

cm = confusion_matrix(b, predication_a)
print(cm)

[1 1 1 1]
[[0 1]
 [0 3]]


In [116]:
accuracy = accuracy_score(b, predication_a)
print(accuracy)

0.75


In [118]:
preci = precision_score(b, predication_a)
print(preci)

0.75


In [120]:
rs = recall_score(b,predication_a)
print(rs)

1.0


In [122]:
f1 = f1_score(b,predication_a)
print(f1)

0.8571428571428571
